# Generated by Django 5.2.17 on 2026-09-05 10:37

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('points', models.PositiveIntegerField(default=100)),
                ('repeatable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('rule', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleRegistrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('spreadsheet_id', models.CharField(max_length=240)),
                ('worksheet_name', models.CharField(max_length=160)),
                ('column_mappings', models.JSONField(default=dict)),
                ('unique_identifiers', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_cursor', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=160)),
                ('job_role', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('qr_token', models.CharField(default=core.models.token, editable=False, max_length=64, unique=True)),
                ('pass_number', models.CharField(default=core.models.pass_number, editable=False, max_length=32, unique=True)),
                ('registration_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('time_limit_seconds', models.PositiveSmallIntegerField()),
                ('base_points', models.PositiveIntegerField(default=1000)),
                ('host_note', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('is_open', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PALIntegrationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_result_id', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('launch_nonce', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('complete', 'COMPLETE'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('career_role', models.CharField(blank=True, max_length=200)),
                ('ai_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('career_hp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('recommendation_summary', models.TextField(blank=True)),
                ('risk_card_url', models.URLField(blank=True)),
                ('payload_checksum', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pal_results', to='core.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('sequence', models.PositiveSmallIntegerField(unique=True)),
                ('state', models.CharField(choices=[('draft', 'DRAFT'), ('lobby', 'LOBBY'), ('question_open', 'QUESTION OPEN'), ('question_closed', 'QUESTION CLOSED'), ('reveal', 'REVEAL'), ('leaderboard', 'LEADERBOARD'), ('finished', 'FINISHED')], default='draft', max_length=30)),
                ('prize_eligible', models.BooleanField(default=True)),
                ('speed_bonus_enabled', models.BooleanField(default=False)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.question')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorised', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('active', 'ACTIVE'), ('complete', 'COMPLETE'), ('void', 'VOID')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('official_score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('total_response_ms', models.PositiveIntegerField(default=0)),
                ('final_daily_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_attempts', to='core.participant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='core.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.UUIDField(unique=True)),
                ('is_correct', models.BooleanField()),
                ('base_points_awarded', models.PositiveIntegerField(default=0)),
                ('speed_points_awarded', models.PositiveIntegerField(default=0)),
                ('response_duration_ms', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='core.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='core.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='core.answerchoice')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_value', models.IntegerField()),
                ('new_value', models.IntegerField()),
                ('reason', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.quizattempt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=40)),
                ('points', models.IntegerField()),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xp_transactions', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField()),
                ('source_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('facilitator', models.CharField(blank=True, max_length=200)),
                ('format', models.CharField(choices=[('face', 'FACE-TO-FACE'), ('virtual', 'VIRTUAL'), ('hybrid', 'HYBRID')], default='face', max_length=20)),
                ('audience', models.CharField(blank=True, max_length=240)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('day', 'starts_at'),
                'indexes': [models.Index(fields=['day', 'starts_at'], name='core_sessio_day_c198cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField()),
                ('source', models.CharField(default='qr', max_length=30)),
                ('is_override', models.BooleanField(default=False)),
                ('override_note', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='google_sheet', max_length=40)),
                ('source_row_key', models.CharField(blank=True, max_length=160)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_registrations', to='core.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.googleregistrationsource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WinnerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=20)),
                ('calculated_rank', models.PositiveIntegerField()),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score_snapshot', models.PositiveIntegerField()),
                ('correct_snapshot', models.PositiveIntegerField(default=0)),
                ('response_ms_snapshot', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('provisional', 'PROVISIONAL'), ('verified', 'VERIFIED'), ('winner', 'WINNER'), ('disqualified', 'DISQUALIFIED')], default='provisional', max_length=20)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner_records', to='core.participant')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField()),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='core.activity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_completions', to='core.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'activity'), name='unique_participant_activity')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='core.badge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='core.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'badge'), name='unique_participant_badge')],
            },
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.UniqueConstraint(fields=('question', 'number'), name='unique_question_choice_number'),
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 4)), name='choice_number_1_to_4'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'number'), name='unique_quiz_question_number'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'official_score', 'correct_count'], name='core_quizat_quiz_id_047eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('authorised', True), models.Q(('state', 'void'), _negated=True)), fields=('participant', 'quiz'), name='unique_authorised_attempt'),
        ),
        migrations.AddConstraint(
            model_name='quizresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_response'),
        ),
        migrations.AddIndex(
            model_name='scoretransaction',
            index=models.Index(fields=['participant', 'category'], name='core_scoret_partici_de27df_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session', 'checked_in_at'], name='core_attend_session_393633_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('participant', 'session'), name='unique_attendance'),
        ),
        migrations.AddConstraint(
            model_name='sessionregistration',
            constraint=models.UniqueConstraint(fields=('participant', 'session'), name='unique_session_registration'),
        ),
        migrations.AddConstraint(
            model_name='winnerrecord',
            constraint=models.UniqueConstraint(fields=('participant', 'quiz', 'scope'), name='unique_winner_scope'),
        ),
    ]
