# Generated by Django 5.2.17 on 2026-09-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scoringrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(default='CRDB × Predictive Analytics Lab Learning Week Experience', max_length=240)),
                ('start_date', models.DateField(default='2026-09-07')),
                ('end_date', models.DateField(default='2026-09-10')),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=64)),
                ('registration_url', models.URLField(blank=True)),
                ('programme_visible', models.BooleanField(default=True)),
                ('leaderboard_visible', models.BooleanField(default=True)),
                ('grand_prize_visible', models.BooleanField(default=False)),
                ('qr_behavior', models.CharField(default='persistent_pass', max_length=40)),
                ('support_contact', models.CharField(blank=True, max_length=200)),
                ('pal_enabled', models.BooleanField(default=True)),
                ('google_forms_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('accent', models.CharField(default='#df1f26', max_length=12)),
                ('background_treatment', models.CharField(default='grid', max_length=40)),
                ('hero_label', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('intro_copy', models.TextField(blank=True)),
                ('result_language', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_order',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('random', 'Randomized')], default='fixed', max_length=16),
        ),
        migrations.AddField(
            model_name='quiz',
            name='auto_close_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='contributes_to_weekly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='daily_leaderboard_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='internal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='participant_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_order',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('random', 'Random')], default='fixed', max_length=16),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme_key',
            field=models.CharField(default='infrastructure', max_length=40),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tie_break_method',
            field=models.CharField(default='correct_time_completion', max_length=80),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='state',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('scheduled', 'SCHEDULED'), ('lobby', 'LOBBY OPEN'), ('question_open', 'LIVE'), ('question_closed', 'QUESTION CLOSED'), ('reveal', 'ANSWER REVEAL'), ('leaderboard', 'LEADERBOARD'), ('finished', 'FINISHED'), ('verified', 'VERIFIED'), ('archived', 'ARCHIVED')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('quiz', 'Quiz'), ('session', 'Session'), ('pal_challenge', 'PAL AI Jobs'), ('expo_activity', 'Expo Activity'), ('aiot_demo', 'AIoT Demo'), ('survey', 'Survey'), ('custom_challenge', 'Custom Challenge')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('day', models.PositiveSmallIntegerField(default=1)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered only'), ('hidden', 'Hidden')], default='registered', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('points_enabled', models.BooleanField(default=False)),
                ('completion_points', models.PositiveIntegerField(default=0)),
                ('requires_registration', models.BooleanField(default=False)),
                ('requires_checkin', models.BooleanField(default=False)),
                ('show_on_dashboard', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('cover_asset', models.CharField(blank=True, max_length=240)),
                ('instructions', models.TextField(blank=True)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='core.activity')),
                ('quiz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='core.quiz')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='core.session')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='core.experiencetheme')),
            ],
            options={
                'ordering': ('day', 'start_at', 'title'),
                'indexes': [models.Index(fields=['status', 'show_on_dashboard', 'start_at'], name='core_experi_status_77d883_idx'), models.Index(fields=['type', 'day'], name='core_experi_type_d82c1b_idx')],
            },
        ),
    ]
