# Generated by Django 5.2.17 on 2026-09-06 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventsettings_experiencetheme_activity_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scoretransaction',
            name='core_scoret_partici_de27df_idx',
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='competition_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='learning_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='source_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='source_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('void', 'VOID'), ('reversed', 'REVERSED')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scoretransaction',
            index=models.Index(fields=['participant', 'category', 'status'], name='core_scoret_partici_2cabc9_idx'),
        ),
        migrations.AddIndex(
            model_name='scoretransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='core_scoret_source__e690bb_idx'),
        ),
    ]
