# Generated by Django 5.2.17 on 2026-09-07 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_scoretransaction_core_scoret_partici_de27df_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('full_name',)},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['checked_in_at'], name='core_attend_checked_e1b335_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['department'], name='core_partic_departm_5359ba_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_active', 'full_name'], name='core_partic_is_acti_62f587_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['participant', 'quiz'], name='core_quizat_partici_2eacdb_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['authorised', 'state'], name='core_quizat_authori_4f8e52_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponse',
            index=models.Index(fields=['question', 'selected_choice'], name='core_quizre_questio_913987_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponse',
            index=models.Index(fields=['question', 'submitted_at'], name='core_quizre_questio_e4b0d2_idx'),
        ),
    ]
