# Generated by Django 5.2.17 on 2026-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='allowed_email_domains',
            field=models.CharField(blank=True, help_text='Comma-separated domains allowed to self-register, e.g. crdbbank.co.tz. Leave blank to accept any email address.', max_length=400),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='self_registration_collects_department',
            field=models.BooleanField(default=True, help_text='Ask for department during self-registration. It drives the analytics breakdown.'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='self_registration_enabled',
            field=models.BooleanField(default=True, help_text='Let people join by entering their email, without being pre-loaded from a spreadsheet or Google Form.'),
        ),
    ]
