# Generated by Django 5.2.17 on 2026-09-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventsettings_allowed_email_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='auto_run',
            field=models.BooleanField(default=True, help_text='Start once and the whole round plays itself: every question opens and closes on its own timer, with no host action between questions.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='auto_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lobby_seconds',
            field=models.PositiveSmallIntegerField(default=10, help_text='Countdown shown after starting, before question 1 opens.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reveal_seconds',
            field=models.PositiveSmallIntegerField(default=8, help_text='Seconds spent showing the correct answer between questions.'),
        ),
    ]
